spring.application.name=Weather Forecast
server.port=8080


openweathermap.api.key=${OPENWEATHERMAP_API_KEY:YOUR_API_KEY_HERE}
openweathermap.api.base-url=https://api.openweathermap.org/data/2.5
openweathermap.api.geo-url=https://api.openweathermap.org/geo/1.0


spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
